config/routes.rb
RenanCodeCom::Application.routes.draw do
  root :to => 'home#index'
  
  get "home/index"

  devise_for :users
  
  resources :championships do
  	resources :games
  	
  	resources :teams

    post "dashboard" => "dashboard#updategame", as: "dashboard"

    get 'dashboard', to: 'dashboard#show', as: 'dashboard'
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  def show
  	@championship = current_user.championships.find(params[:championship_id])

    phase = params[:phase].to_i
    if phase == 0
      phase = 1
    end

    if @championship.rule_id == 3
      @games = @championship.games.find_games_playoffs(@championship)
      @games = @championship.games
    elsif phase == 2
      @games = @championship.games.find_games_playoffs(@championship)
      @ranking = Ranking.buildRanking(@championship)
    else
      @games = @championship.games.find_games_perpage(@championship, params[:page])
      @ranking = Ranking.buildRanking(@championship)
    end
  end

  def updategame
    @championship = current_user.championships.find(params[:championship_id])
    
    @game = @championship.games.find(params[:game_id])
    @game.placar1 = params[:placar1]
    @game.placar2 = params[:placar2]
    @game.save

    respond_to do |format|
      format.html { redirect_to :back, notice: 'Game ' + @game.id.to_s + ' was successfully updated.' }
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper

  def team_description(game, index)
    if index == 1 && !game.team1.nil?
      return game.team1.name
    elsif index == 1
      if (game.duel1.include? "A") || (game.duel1.include? "B") || (game.duel1.include? "C") || (game.duel1.include? "D") || (game.duel1.include? "E") || (game.duel1.include? "F") || (game.duel1.include? "G") 
        return game.duel1[0].to_s + "º Grupo " + game.duel1[1].to_s
      else
        if game.duel1.to_i < 0
          duel1 = game.duel1.to_i * -1
          return "Perd. " + duel1.to_s
        else
          return "Venc. " + game.duel1.to_s
        end
      end
    elsif index == 2 && !game.team2.nil?
      return game.team2.name
    else
      if (game.duel2.include? "A") || (game.duel2.include? "B") || (game.duel2.include? "C") || (game.duel2.include? "D") || (game.duel2.include? "E") || (game.duel2.include? "F") || (game.duel2.include? "G") || (game.duel2.include? "H") || (game.duel2.include? "I") || (game.duel2.include? "J") || (game.duel2.include? "K") || (game.duel2.include? "L") || (game.duel2.include? "M") 
        return game.duel2[0].to_s + "º Grupo " + game.duel2[1].to_s
	  else
      if game.duel2.to_i < 0
        duel2 = game.duel2.to_i * -1
        return "Perd. " + duel2.to_s
      else
        return "Venc. " + game.duel2.to_s
      end	  	
	  end
    end
  end

end

app/views/dashboard/_games.html.erb
<% stage = nil %>
<% games.each do |g| %>
  <div class="row">
    <div class="span4">
      <% if g.stage != stage %>
        <h6 style="text-align: center;"> <%= g.stage %> </h6>
      <% end %>
      <div class="highlight">
        <%= form_tag(championship_dashboard_path(championship), :method => "post", :class => "form-inline") do %>
          <%= hidden_field_tag(:game_id, g.id) %> 
          <%= g.id.to_s %> |
          <% if g.team1.nil? %>
            <%= text_field_tag(:placar1, g.placar1, placeholder: team_description(g, 1), maxlength: 2, in: 0...99, style: 'width: 80px;') %>
          <% else %>
            <%= image_tag(g.team1.logo, alt: g.team1.name, height: 30, width: 30) unless g.team1.nil? %> <%= g.team1.abbreviation.to_s %>
            <%= text_field_tag(:placar1, g.placar1, maxlength: 2, in: 0...99, style: 'width: 20px;') %>
          <% end %>
          <%= "x" %>
          <% if g.team2.nil? %>
            <%= text_field_tag(:placar2, g.placar2, placeholder: team_description(g, 2), maxlength: 2, in: 0...99, style: 'width: 80px;') %>
          <% else %>
            <%= text_field_tag(:placar2, g.placar2, maxlength: 2, in: 0...99, style: 'width: 20px;') %>
            <%= image_tag(g.team2.logo, alt: g.team2.name, height: 30, width: 30) unless g.team2.nil? %> <%= g.team2.abbreviation.to_s %>
          <% end %>
          <%= button_tag("Ok", :class => 'btn btn-primary') %>
        <% end %>
      </div>
      <hr>
    </div>
  </div>
  <% stage = g.stage %>
<% end %>

app/views/dashboard/_ranking.html.erb
<% group = nil %>

<% ranking.each do |r| %>
  <% if !group.nil? && r.groups != group && r.rule_id != 2 %>
      </tbody>
    </table>
  <% end %>

  <% if r.groups != group %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th colspan="9">
            <center>Grupo <%= r.groups %></center>
          </th>
        </tr>
        <tr>
          <th colspan="2">Classificação</th>
          <th>P</th>
          <th>J</th>
          <th>V</th>
          <th>E</th>
          <th>D</th>
          <th>GP</th>
          <th>GC</th>
          <th>SG</th>
        </tr>
      </thead>
      <tbody>
  <% end %>
  <tr>
    <td><%= r.position %>º</td>
    <td width="60%"><%= image_tag(r.team_logo, alt: r.team_name, height: 21, width: 21) %>&nbsp;&nbsp;<%= r.team_name %></td>
    <td><%= r.points %></td>
    <td><%= r.games %></td>
    <td><%= r.victory %></td>
    <td><%= r.draw %></td>
    <td><%= r.defeat %></td>
    <td><%= r.gols_for %></td>
    <td><%= r.gols_against %></td>
    <td><%= r.gols_balance %></td>
  </tr>
      
  <% group = r.groups %>
<% end %>

<% if !group.nil? || ranking[1].rule_id == 2 %>
      </tbody>
  </table>
<% end %>

app/views/dashboard/show.html.erb
<div class="page-header">
  <h1 align="center"><%= @championship.name %></h1>
</div>
<div class="navbar-inner">
  <br>
  <% if @championship.rule_id == 3  %>
    <%= render :partial => 'games', :locals => {:championship => @championship, :games => @games} %> 
  <% else %>
    <div class="span7">
        <%= render :partial => 'ranking', :locals => {:ranking => @ranking} %>
    </div>
    <div class="span4">
      <%= render :partial => 'games', :locals => {:championship => @championship, :games => @games} %> 
      <center>
        <% if @championship.rule_id != 3 && params[:phase] != '2' %>
            <%= will_paginate @games %>
        <% end %>
        <% if @championship.rule_id == 1 %>
          <div class="pagination">
            <ul>
              <li><%= link_to "Classificação" %></li>
              <li><%= link_to "Eliminatórias", :phase => "2" %></li>
            </ul>
          </div>
          <% end %>
      </center>
    </div>

  <% end %>
</div>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
                  championships_path, :class => 'btn' %>
  </div>
  