config/routes.rb
RenanCodeCom::Application.routes.draw do
  root :to => 'home#index'
  
  get "home/index"

  devise_for :users
  
  resources :championships do
  	resources :games
  	
  	resources :teams

    post "dashboard" => "dashboard#updategame", as: "dashboard"

    get 'dashboard', to: 'dashboard#show', as: 'dashboard'
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :championships_attributes, :championship_id, :groups, :phase_id, :placar1, :placar2, :stage, :team1_id, :team2_id, :duel1, :duel2
  
  belongs_to :team1, :foreign_key => "team1_id", :class_name => "Team"
  belongs_to :team2, :foreign_key => "team2_id", :class_name => "Team"
  belongs_to :phase
  belongs_to :championship

  def self.find_games_perpage(championship, page)
    @championship = championship
    
    stages = @championship.games.where(phase_id: 1).select("distinct stage")
    pages = @championship.games.where(stage: stages[0].stage).count
    
    @games = @championship.games.where(:phase_id => 1).order(:stage).paginate(:page => page, :per_page => pages)
  end

  def self.find_games_playoffs(championship)
    @championship = championship

    buildPlayoffs

    @games = @championship.games.where(phase_id: 2)
  end

  def self.buildPlayoffs
    @championship.games.where(phase_id: 2).order(:id).each do |g|
      if (g.duel2.include? "A") || (g.duel2.include? "B") || (g.duel2.include? "C") || (g.duel2.include? "D") || (g.duel2.include? "E") || (g.duel2.include? "F") || (g.duel2.include? "G") || (g.duel2.include? "H") || (g.duel2.include? "I") || (g.duel2.include? "J") || (g.duel2.include? "K") || (g.duel2.include? "L") || (g.duel2.include? "M") 

        game = @championship.games.find(g.id)

        count = @championship.games.where(phase_id: 1, groups: g.duel1[1], placar1: nil, placar2: nil).count
        if count > 0
          game.team1_id = nil
          game.team2_id = nil
          game.placar1 = nil
          game.placar2 = nil
          game.save
          next
        end

        count = @championship.games.where(:phase_id => 1, :groups => g.duel2[1], :placar1 => nil, :placar2 => nil).count
        if count > 0
          game.team1_id = nil
          game.team2_id = nil
          game.placar1 = nil
          game.placar2 = nil
          game.save
          next
        end

        ranking = Ranking.buildRanking(@championship)
        game.team1_id = self.find_team(ranking, g.duel1[0], g.duel1[1])
        game.team2_id = self.find_team(ranking, g.duel2[0], g.duel2[1])
        game.save
      else
        game = @championship.games.find(g.id)

        if (! g.duel1.empty?)
          if g.duel1.to_i < 0
            duel1 = g.duel1.to_i * -1
          else
            duel1 = g.duel1
          end

          game1 = @championship.games.find(duel1)
          if game1.placar1.nil? || game1.placar2.nil?
            game.placar1 = nil
            game.placar2 = nil
            game.team1_id = nil
          end

          if g.duel1.to_i < 0
            game.team1_id = self.find_team_loser(game1)
          else
            game.team1_id = self.find_team_victory(game1)
          end          
        end

        if (! g.duel2.empty?)
          if g.duel2.to_i < 0
            duel2 = g.duel2.to_i * -1
          else
            duel2 = g.duel2
          end

          game2 = @championship.games.find(duel2)
          if game2.placar1.nil? || game2.placar2.nil?
            game.placar1 = nil
            game.placar2 = nil
            game.team2_id = nil
          end

          if g.duel2.to_i < 0
            game.team2_id = self.find_team_loser(game2)
          else
            game.team2_id = self.find_team_victory(game2)
          end          
        end

        game.save
      end
    end
  end

  private

  def self.find_team(ranking, position, groups)
    ranking.each do |r|
      if r.position.to_i == position.to_i && r.groups.to_s == groups.to_s
        return r.team_id
      end
    end
  end

  def self.find_team_victory(game)
    if game.placar1.nil? || game.placar2.nil?
      return nil
    end

    if game.placar1 > game.placar2
      return game.team1_id
    elsif game.placar2 > game.placar1
      return game.team2_id
    end
  end

  def self.find_team_loser(game)
    if game.placar1.nil? || game.placar2.nil?
      return nil
    end

    if game.placar1 < game.placar2
      return game.team1_id
    elsif game.placar2 < game.placar1
      return game.team2_id
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @championship = current_user.championships.find(params[:championship_id])
    @games = @championship.games.paginate(:page => params[:page], :per_page => 15)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  def show
    @championship = current_user.championships.find(params[:championship_id])
    @game = @championship.games.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  def new
    @championship = current_user.championships.find(params[:championship_id])
    @game = @championship.games.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  def edit
    @championship = current_user.championships.find(params[:championship_id])
    @game = @championship.games.find(params[:id])
  end

  def create
    @championship = current_user.championships.find(params[:championship_id])
    @game = @championship.games.build(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to championship_games_url(@championship), notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @championship = current_user.championships.find(params[:championship_id])
    @game = @championship.games.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to championship_games_url(@championship), notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @championship = current_user.championships.find(params[:championship_id])
    @game = @championship.games.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to championship_games_url(@championship) }
      format.json { head :no_content }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= simple_form_for [@championship, @game], :html => { :class => 'form-horizontal' } do |f| %>
    <%= f.input :team1_id, collection: @championship.teams, prompt: "Select your team 1" %>
    <%= f.input :team2_id, collection: @championship.teams, prompt: "Select your team 2" %>
    <%= f.input :phase_id, collection: Phase.all, prompt: "Select your phase" %>
    <%= f.input :stage %>
    <%= f.input :groups %>
    <%= f.input :duel1 %>
    <%= f.input :duel2 %>
    <div class="form-actions">
      <%= link_to t('.back', :default => t("helpers.links.back")),
                  championship_games_path(@championship), :class => 'btn' %>
      <%= f.button :submit, :class => 'btn-primary' %>
    </div>
<% end %>

app/views/games/edit.html.erb
<%- model_class = Game -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/games/index.html.erb
<%- model_class = Game -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:championship_id) %></th>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:team1_id) %></th>
      <th><%= model_class.human_attribute_name(:placar1) %></th>
      <th><%= model_class.human_attribute_name(:team2_id) %></th>
      <th><%= model_class.human_attribute_name(:placar2) %></th>
      <th><%= model_class.human_attribute_name(:phase_id) %></th>
      <th><%= model_class.human_attribute_name(:groups) %></th>
      <th><%= model_class.human_attribute_name(:stage) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to game.championship.name, championship_game_path(@championship, game) %></td>
        <td><%= link_to game.id, championship_game_path(@championship, game) %></td>
        <td><%= game.team1.name unless game.team1.nil? %></td>
        <td><%= game.placar1 %></td>
        <td><%= game.team2.name unless game.team2.nil? %></td>
        <td><%= game.placar2 %></td>
        <td><%= game.phase.name %></td>
        <td><%= game.groups %></td>
        <td><%= game.stage %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_championship_game_path(@championship, game), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      championship_game_path(@championship, game),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @games %>

<%= link_to t('.back', :default => t("helpers.links.back")),
            championship_path(@championship), :class => 'btn'  %>          

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_championship_game_path(@championship),
            :class => 'btn btn-primary' %>

app/views/games/new.html.erb
<%- model_class = Game -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/games/show.html.erb
<%- model_class = Game -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:id) %>:</strong></dt>
  <dd><%= @game.id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:championship_id) %>:</strong></dt>
  <dd><%= @game.championship_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:team1_id) %>:</strong></dt>
  <dd><%= @game.team1_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:placar1) %>:</strong></dt>
  <dd><%= @game.placar1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:team2_id) %>:</strong></dt>
  <dd><%= @game.team2_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:placar2) %>:</strong></dt>
  <dd><%= @game.placar2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phase_id) %>:</strong></dt>
  <dd><%= @game.phase_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:groups) %>:</strong></dt>
  <dd><%= @game.groups %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stage) %>:</strong></dt>
  <dd><%= @game.stage %></dd>
  <dt><strong><%= model_class.human_attribute_name(:duel1) %>:</strong></dt>
  <dd><%= @game.duel1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:duel2) %>:</strong></dt>
  <dd><%= @game.duel2 %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              championship_games_path(@championship), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_championship_game_path(@championship, @game), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              championship_game_path(@championship, @game),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>